sudo: false
language: node_js
node_js:
  - 'iojs'
  - 5
  - 4
  - '0.12'
  - '0.10'
after_script:
  - npm install istanbul-coveralls
  - npm run-script coverage
  - node node_modules/.bin/istanbul-coveralls
